version: 2
updates:
  - package-ecosystem: npm
    directory: /package/frontend
    schedule:
      interval: weekly
    groups:
      frontend-dependencies:
        patterns: ["*"]
  - package-ecosystem: pip
    directory: /package/backend
    schedule:
      interval: weekly
    groups:
      backend-dependencies:
        patterns: ["*"]
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
